services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: dev
      MARIADB_PASSWORD: qwerty
      MARIADB_DATABASE: devApp
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db